spring.application.name=config-serveur
spring.cloud.compatibility-verifier.enabled=false

server.port:9101
#spring.cloud.config.server.git.uri=https://github.com/ESPHEREAPI/mcommerce-config-repo.git
#pour redirectionlocal utiliser ceci 
spring.cloud.config.server.git.uri=file://${user.home}/cloud-config-gescom

